- name: Install System Packages 2 (unzip)
  become: true
  apt:
      name: ["unzip"]
  tags:
      - install
      - neovim
      - core

- name: Install System Packages 3 (the rest)
  become: true
  apt:
      name:
          [
              "curl",
              "htop",
              "golang",
              "python3-pip"
          ]
  tags:
      - install
      - core
